"""
Security-response-header middleware (CASA 4.1.1 TLS/HSTS, 5.1.7 XSS/CSP, 6.2.1 fingerprinting).

Closes the entire Phase-0 DAST warning list on moltbot-fastapi:
  ZAP  [10021] X-Content-Type-Options · [10035] HSTS · [10049] Storable/Cacheable
       [10015] Cache-control · [90004] Cross-Origin-Resource-Policy
  Fluid 043 CSP · 131 HSTS · 132 X-Content-Type-Options · 440 Permissions-Policy

This is a pure-ASGI middleware, NOT a BaseHTTPMiddleware, and is mounted OUTERMOST so it
stamps EVERY response — including ones short-circuited by an inner middleware (idempotency
cache hit, 413 body-cap reject) and error responses raised inside the stack. A header set
only on the happy path is a header a scanner will catch you missing.

CSP note: this service is a pure JSON API. `default-src 'none'` is the correct, strictest
policy — there is no page to render, so nothing can break. The one exception is the
interactive Swagger/ReDoc UI, which is served ONLY when DEBUG=true (see main.py); in that
case we relax exactly enough for the docs UI and no more. Production never takes that branch.
"""

from starlette.datastructures import MutableHeaders
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from ..config import settings

# A JSON API renders nothing: deny every fetch/exec/embed vector outright.
_CSP_API = (
    "default-src 'none'; "
    "frame-ancestors 'none'; "
    "base-uri 'none'; "
    "form-action 'none'; "
    "object-src 'none'"
)

# DEBUG-only: Swagger UI pulls its bundle from the jsdelivr CDN and inlines styles.
# Never served in production (docs are disabled there), so this cannot weaken prod.
_CSP_DOCS = (
    "default-src 'none'; "
    "script-src 'self' https://cdn.jsdelivr.net 'unsafe-inline'; "
    "style-src 'self' https://cdn.jsdelivr.net 'unsafe-inline'; "
    "img-src 'self' data: https://fastapi.tiangolo.com; "
    "font-src 'self' https://cdn.jsdelivr.net; "
    "connect-src 'self'; "
    "frame-ancestors 'none'; "
    "base-uri 'none'; "
    "form-action 'self'; "
    "object-src 'none'"
)

_PERMISSIONS_POLICY = (
    "accelerometer=(), autoplay=(), camera=(), display-capture=(), "
    "encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), "
    "magnetometer=(), microphone=(), midi=(), payment=(), "
    "picture-in-picture=(), usb=(), xr-spatial-tracking=()"
)


def security_headers() -> dict[str, str]:
    """
    The single source of truth for the CASA/DAST security-header set.

    Exported so BOTH stampers use the SAME values and can't drift:
      - SecurityHeadersMiddleware (normal responses: 200/401/404/413/429/307/CORS)
      - the unhandled-exception handler in main.py (the 500 path, which is generated by
        Starlette's ServerErrorMiddleware OUTSIDE this middleware and therefore cannot be
        reached by it — the Phase-4 critic's Defect 1).
    """
    return {
        # Transport (CASA 4.1.1). 2 years, subdomains, preload-eligible.
        "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
        # Content sniffing / clickjacking / referrer leakage.
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "Referrer-Policy": "strict-origin-when-cross-origin",
        # Cross-origin isolation (ZAP 90004 — the header ZAP's baseline flags and most
        # teams miss; BuzzClan failed their first scan on exactly this).
        "Cross-Origin-Resource-Policy": "same-origin",
        "Cross-Origin-Opener-Policy": "same-origin",
        "Permissions-Policy": _PERMISSIONS_POLICY,
        "Content-Security-Policy": _CSP_DOCS if settings.DEBUG else _CSP_API,
        # API responses carry Google/user data — never cacheable by a proxy or browser
        # (ZAP 10049 Storable/Cacheable + 10015 Re-examine Cache-control).
        "Cache-Control": "no-store",
        "Pragma": "no-cache",
    }


class SecurityHeadersMiddleware:
    """Stamp the CASA/DAST security-header set on every normal HTTP response."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                for name, value in security_headers().items():
                    headers[name] = value

                # Version fingerprinting (CASA 6.2.1). NOTE: uvicorn writes its own
                # `Server: uvicorn` header BELOW the ASGI layer, so it is not present here
                # and this `del` cannot remove it — that one is suppressed by
                # `--no-server-header` on the uvicorn start command (render.yaml). This del
                # is belt-and-suspenders for any header a downstream layer might set.
                # Render's edge also mirrors `x-render-origin-server: uvicorn`, which is the
                # provider's and un-removable from app code (infra-attributed, PHASE_4 §4.11).
                for h in ("server", "x-powered-by"):
                    if h in headers:
                        del headers[h]

            await send(message)

        await self.app(scope, receive, send_with_headers)
