"""
Admin endpoints — operational maintenance, gated by API_SECRET_KEY.

Currently exposes:
  GET  /admin/qstash/schedules       — list every QStash schedule + status
                                       (active=tied to a pending recurring
                                       reminder; orphan=schedule but no
                                       matching reminder; unknown=can't tell).
  POST /admin/qstash/cleanup-orphans — delete every orphan schedule.
  POST /admin/qstash/cleanup-all     — nuke EVERY schedule (requires
                                       ?confirm=DELETE_ALL_SCHEDULES query
                                       param to prevent accidents).

Auth: every request must carry `Authorization: Bearer <API_SECRET_KEY>`. The
API_SECRET_KEY is auto-generated by Render at first deploy (see render.yaml).
You can read it from the Render dashboard for the moltbot-fastapi service.
"""

from __future__ import annotations

import json
import logging
from typing import List, Optional

from fastapi import APIRouter, Header, HTTPException, Query, status
from pydantic import BaseModel

from ..config import settings
from ..core.database import db
from ..services.qstash_service import qstash_service

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/admin", tags=["Admin"])


def _require_admin(authorization: Optional[str]) -> None:
    """
    Auth gate. Compares the bearer token against settings.API_SECRET_KEY.
    Constant-time comparison would be ideal but the token is provisioned by
    Render and shared — the threat model here is misconfiguration, not timing.
    """
    if not settings.API_SECRET_KEY:
        # Misconfigured deploy — fail closed. We never want admin endpoints
        # open just because the secret wasn't set.
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="API_SECRET_KEY not configured on server",
        )
    expected = f"Bearer {settings.API_SECRET_KEY}"
    if authorization != expected:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing Authorization header",
        )


class QStashSchedule(BaseModel):
    schedule_id: str
    cron: Optional[str] = None
    destination: Optional[str] = None
    reminder_id: Optional[int] = None
    user_id: Optional[str] = None
    status: str  # "active" | "orphan" | "unknown"
    reason: Optional[str] = None
    created_at: Optional[str] = None


def _parse_schedule_body(body) -> tuple[Optional[int], Optional[str]]:
    """
    QStash returns the body as a JSON string (or sometimes already parsed).
    Pull reminder_id and user_id if present so we can match to the DB.
    """
    if not body:
        return None, None
    try:
        if isinstance(body, str):
            body = json.loads(body)
        if isinstance(body, dict):
            rid = body.get("reminder_id")
            uid = body.get("user_id")
            return (
                int(rid) if rid is not None else None,
                str(uid) if uid is not None else None,
            )
    except (json.JSONDecodeError, TypeError, ValueError):
        pass
    return None, None


def _schedule_attr(s, *names: str):
    """
    The QStash SDK returns schedule objects whose field shape varies by version
    (sometimes camelCase attrs on a dataclass, sometimes a dict). Try each
    plausible name and return the first non-None.
    """
    for n in names:
        if isinstance(s, dict):
            v = s.get(n)
        else:
            v = getattr(s, n, None)
        if v is not None:
            return v
    return None


async def _classify_schedules() -> List[QStashSchedule]:
    """
    Pull all QStash schedules, cross-reference with the DB, and return them
    annotated with status:
      active  — matches a pending recurring reminder in DB.
      orphan  — schedule exists but no matching pending reminder.
      unknown — schedule body has no parseable reminder_id (legacy / hand-made).
    """
    if not qstash_service.is_configured:
        raise HTTPException(503, "QStash not configured")

    schedules = qstash_service.list_schedules()
    logger.info(f"Found {len(schedules)} QStash schedules")

    # Pull all currently-active recurring reminders so we can match by
    # qstash_schedule_id. This avoids a per-row DB lookup.
    active_schedule_ids: set[str] = set()
    try:
        client = db._client
        if client:
            resp = (
                client.table("tbl_clawdbot_reminders")
                .select("qstash_schedule_id")
                .eq("status", "pending")
                .neq("recurrence", "none")
                .execute()
            )
            for row in (resp.data or []):
                sid = row.get("qstash_schedule_id")
                if sid:
                    active_schedule_ids.add(sid)
    except Exception as e:
        logger.warning(f"Could not fetch active reminders: {e}")

    out: List[QStashSchedule] = []
    for s in schedules:
        sid = _schedule_attr(s, "schedule_id", "scheduleId")
        cron = _schedule_attr(s, "cron")
        destination = _schedule_attr(s, "destination")
        body = _schedule_attr(s, "body")
        created_at = _schedule_attr(s, "created_at", "createdAt")
        rid, uid = _parse_schedule_body(body)

        if not sid:
            continue

        if sid in active_schedule_ids:
            classification = ("active", "matches active reminder by schedule_id")
        elif rid is None:
            classification = ("unknown", "schedule body has no reminder_id")
        else:
            classification = ("orphan", f"reminder {rid} not found / not pending")

        out.append(
            QStashSchedule(
                schedule_id=sid,
                cron=cron,
                destination=destination,
                reminder_id=rid,
                user_id=uid,
                status=classification[0],
                reason=classification[1],
                created_at=str(created_at) if created_at else None,
            )
        )
    return out


@router.get("/qstash/schedules")
async def list_qstash_schedules(
    authorization: Optional[str] = Header(None),
):
    """List every QStash schedule with a cross-referenced DB status."""
    _require_admin(authorization)
    schedules = await _classify_schedules()
    by_status: dict[str, int] = {}
    for s in schedules:
        by_status[s.status] = by_status.get(s.status, 0) + 1
    return {
        "code": 200,
        "message": f"Listed {len(schedules)} schedules",
        "data": {
            "total": len(schedules),
            "by_status": by_status,
            "schedules": [s.model_dump() for s in schedules],
        },
        "error": None,
    }


@router.post("/qstash/cleanup-orphans")
async def cleanup_orphan_schedules(
    authorization: Optional[str] = Header(None),
    include_unknown: bool = Query(
        False,
        description="Also delete schedules whose body has no parseable reminder_id (true orphans from before the schema). Default false to be conservative.",
    ),
):
    """
    Delete every schedule classified as 'orphan'. Active schedules (those
    tied to a pending recurring reminder in the DB) are preserved.

    With include_unknown=true, also deletes 'unknown' schedules — those with
    no parseable reminder_id in the body. Useful for cleaning legacy junk.
    """
    _require_admin(authorization)
    schedules = await _classify_schedules()

    targets = [s for s in schedules if s.status == "orphan"]
    if include_unknown:
        targets.extend(s for s in schedules if s.status == "unknown")

    deleted: list[str] = []
    failed: list[dict] = []
    for s in targets:
        try:
            qstash_service.cancel_schedule(s.schedule_id)
            deleted.append(s.schedule_id)
        except Exception as e:
            failed.append({"schedule_id": s.schedule_id, "error": str(e)})

    logger.info(
        f"QStash cleanup: deleted={len(deleted)} failed={len(failed)} "
        f"include_unknown={include_unknown}"
    )
    return {
        "code": 200,
        "message": f"Deleted {len(deleted)} schedules ({len(failed)} failed)",
        "data": {
            "deleted_count": len(deleted),
            "failed_count": len(failed),
            "deleted_ids": deleted,
            "failed": failed,
            "remaining_active": sum(1 for s in schedules if s.status == "active"),
        },
        "error": None,
    }


@router.post("/qstash/cleanup-all")
async def cleanup_all_schedules(
    authorization: Optional[str] = Header(None),
    confirm: str = Query("", description="Must equal 'DELETE_ALL_SCHEDULES'"),
):
    """
    NUCLEAR OPTION — deletes EVERY QStash schedule, including active ones.
    Requires ?confirm=DELETE_ALL_SCHEDULES to fire. Use only if cleanup-orphans
    isn't enough (e.g., the QStash account state is so corrupted that the
    cross-ref isn't trustworthy).

    After this, all currently-pending recurring reminders will silently stop
    firing. The DB will still have qstash_schedule_id values pointing at
    non-existent schedules.
    """
    _require_admin(authorization)
    if confirm != "DELETE_ALL_SCHEDULES":
        raise HTTPException(
            status_code=400,
            detail="Pass ?confirm=DELETE_ALL_SCHEDULES to actually wipe everything",
        )

    schedules = qstash_service.list_schedules()
    deleted: list[str] = []
    failed: list[dict] = []
    for s in schedules:
        sid = _schedule_attr(s, "schedule_id", "scheduleId")
        if not sid:
            continue
        try:
            qstash_service.cancel_schedule(sid)
            deleted.append(sid)
        except Exception as e:
            failed.append({"schedule_id": sid, "error": str(e)})

    logger.warning(
        f"QStash NUCLEAR cleanup: deleted={len(deleted)} failed={len(failed)}"
    )
    return {
        "code": 200,
        "message": f"NUKED {len(deleted)} schedules ({len(failed)} failed)",
        "data": {
            "deleted_count": len(deleted),
            "failed_count": len(failed),
            "deleted_ids": deleted,
            "failed": failed,
        },
        "error": None,
    }
